{{- if .Values.jupyterhub.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-docs
  namespace: argocd
spec:
  destination:
    namespace: cloud-docs
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    helm:
      valueFiles: {}
    path: clusters/helm-charts/cloud-docs
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}